Repository czech-radio/cro-geneea-sdk, pull requests merged in 2022-04, with the labels that each got.

#5 Try to fix Windows build
  .github/workflows/main.yml
  src/cro/geneea/__main__.py
  src/cro/geneea/_domain.py
  tests/test_client.py
  tests/test_domain.py
  tests/test_package.py
Labels: CI

#7 Fix/test
  .github/workflows/main.yml
  README.md
  setup.cfg
  src/__init__.py
  src/cro/geneea/__init__.py
  src/cro/geneea/sdk/__init__.py
  src/cro/geneea/sdk/__main__.py
  src/cro/geneea/sdk/_client.py
  src/cro/geneea/sdk/_domain.py
  tests/test_client.py
  tests/test_domain.py
  tests/test_package.py
Labels: bug, CI

#9 Feature/refactor model
  .gitignore
  README.md
  src/cro/geneea/sdk/__main__.py
  src/cro/geneea/sdk/_client.py
  src/cro/geneea/sdk/_domain.py
  tests/test_client.py
  tests/test_domain.py
Labels: enhancement

#11 Package/small improvements
  .editorconfig
  README.md
  data/input.txt
  data/output.txt
  setup.cfg
  src/cro/geneea/sdk/__init__.py
  src/cro/geneea/sdk/__main__.py
  src/cro/geneea/sdk/_client.py
  src/cro/geneea/sdk/_domain.py
  tests/test_package.py
  tests/test_program.py
Labels: enhancement
